 ##
    # Monitoring
    ##

- name: ensure monitoring keys
  sudo: True
  apt_key: url=http://repos.sensuapp.org/apt/pubkey.gpg state=present
  tags: monitoring

- name: ensure rabbitmq vhost
  sudo: True
  rabbitmq_vhost: name=/sensu state=present
  tags: monitoring

- name: ensure rabbitmq account
  sudo: True
  rabbitmq_user: user=sensu
                 password=sensu
                 vhost=/sensu
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
  tags: monitoring

- name: ensure monitoring repo
  sudo: True
  apt_repository: repo='deb http://repos.sensuapp.org/apt sensu main' state=present update_cache=yes
  tags: monitoring

- name: ensure monitoring package
  sudo: True
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
     - sensu
     - git
  tags: monitoring

- name: ensure monitoring features installed
  sudo: True
  git: repo=https://github.com/sensu/sensu-community-plugins.git dest=/opt/sensu-community-plugins version=master update=yes depth=1
  tags: monitoring

- name: ensure monitoring plugins installed
  sudo: True
  file: src=/opt/sensu-community-plugins/plugins dest=/etc/sensu/plugins/sensu-community-plugins owner=root group=root state=link
  tags: monitoring

- name: ensure monitoring handlers installed
  sudo: True
  file: src=/opt/sensu-community-plugins/handlers dest=/etc/sensu/handlers/sensu-community-plugins owner=root group=root state=link
  tags: monitoring

- name: ensure monitoring configured
  sudo: True
  template: src=config.json.j2 dest=/etc/sensu/config.json mode=0600 owner=sensu group=root
  tags: monitoring

- name: ensure monitoring configured2
  sudo: True
  template: src=client.json.j2 dest=/etc/sensu/conf.d/client.json mode=0600 owner=sensu group=root
  tags: monitoring

- name: ensure rabbitmq ssl files
  sudo: True
  file: state=directory path=/etc/sensu/ssl

- name: Add sensu ssl client certs
  sudo: True
  copy: src={{ item }} dest=/etc/sensu/ssl/{{ item }}
  with_items:
    - client_cert.pem
    - client_key.pem

# TODO: Configure SSL rabbitmq and sensu
- name: ensure monitoring server running
  sudo: True
  service: name={{ item }} state=running enabled=yes
  with_items:
     - sensu-server
     - sensu-api
     - sensu-dashboard
  tags: monitoring

- name: ensure monitoring client running
  sudo: True
  service: name={{ item }} state=running enabled=yes
  with_items:
     - sensu-client
  tags: monitoring
