rootLogger: DEBUG, console, file
logger:
  # log action execution errors for easier debugging
  action: DEBUG
  # reduce the logging for aws, too much is logged under the default INFO
  #com.amazonaws: DEBUG
  com.amazonaws: WARN

  # gateway
  gateway: DEBUG
  #index.gateway: INFO

  # peer shard recovery
  #indices.recovery: DEBUG

  org.apache: WARN

  # discovery; toomegaverbose on trace
  discovery: DEBUG

  index.search.slowlog: TRACE, index_search_slow_log_file

  # log if mlockall worked
  common.jna: DEBUG

additivity:
  index.search.slowlog: false

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

  file:
    type: dailyRollingFile
    file: ${path.logs}/${cluster.name}.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

  index_search_slow_log_file:
    type: dailyRollingFile
    file: ${path.logs}/${cluster.name}_index_search_slowlog.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
